### ISSUE TITLE
Fix SetCell etc argument order

### ISSUE THREAD

**Issue by rafaqz** [cesaraustralia/DynamicGrids.jl#105]
This is confusing:

```julia
rule = SetCell{:H}() do data, index, A, B
```

When the long form method is:
```julia
applyrule(data, rule::SomeRule, (A, B), index)
```

These should have the same argument order so that switching is easy. I propose:
```julia
rule = SetCell{:H}() do data, (A, B), index
```

**Comment by rafaqz** [comment]
@jamesmaino @virgile-baudrot would you like to comment on this? I think it needs to change, and not be like this in the methods paper.

**Comment by virgile-baudrot** [comment]
I approve

**Comment by jamesmaino** [comment]
Looks good to me.
