### ISSUE TITLE
Strange Behaviors for `TransformedOutputs`

### ISSUE THREAD

**Issue by virgile-baudrot** [cesaraustralia/DynamicGrids.jl#169]
The `f` function should never reduce.

## MWE

I used here the `sum` function which is the one used in the [test](https://github.com/cesaraustralia/DynamicGrids.jl/blob/2af4fe194ff861035140016878e1599f40898d9e/test/integration.jl#L308) but failed here.

The simple rule:
```julia
cellRule = Cell{:a,:a}() do state
    state + 10.0
end
array_output = ArrayOutput((a=[1 3],); tspan=1:3)
transformed_output = TransformedOutput(sum, (a=[1 3],); tspan=1:3)
```
The `ArrayOutput` returns:

```julia
julia> sim!(array_output, cellRule)
3-element ArrayOutput{NamedTuple{(:a,), Tuple{Matrix{Int64}}},1} with dimensions: 
  Ti (Time): 1:3 (Sampled - Ordered Regular Intervals)
 (a = [1 3],)
 (a = [11 13],)
 (a = [21 23],)
```

And therefore, I don't know what we should expect from the `sum`function in `TransformedOutput`. Either a map-reduce:

```julia
julia> sum(array_output[1][:a])
4
julia> sum(array_output[2][:a])
24
julia> sum(array_output[3][:a])
44
```
or :

```julia
julia> sum(array_output[1])
1×2 Matrix{Int64}:
 1  3
julia> sum(array_output[2])
1×2 Matrix{Int64}:
 11  13
julia> sum(array_output[3])
1×2 Matrix{Int64}:
 21  23
```

The `TransformedOutput` is then lost:

```julia
julia> sim!(transformed_output, cellRule)
4-element TransformedOutput{Matrix{Int64},1} with dimensions: 
  Ti (Time): 1:3 (Sampled - Ordered Regular Intervals)
 [1 3]
 [21 23]
 [21 23]
 [0 0]
```

Note: Everything work well when using function that does not reduce:

```julia
add1(array) = map(x -> x.+1, array)
transformed_output = TransformedOutput(add1, (a=[1 3],); tspan=1:3)
```

```julia
julia> sim!(transformed_output, cellRule)
4-element TransformedOutput{NamedTuple{(:a,), Tuple{Matrix{Int64}}},1} with dimensions: 
  Ti (Time): 1:3 (Sampled - Ordered Regular Intervals)
 (a = [2 4],)
 (a = [12 14],)
 (a = [22 24],)
 (a = [1 1],)
```
which work fine:

```julia
julia> transformed_output[1] == add1(array_output[1])
true
julia> transformed_output[2] == add1(array_output[2])
true
julia> transformed_output[3] == add1(array_output[3])
true
julia> transformed_output[1][:a] == add1(array_output[1][:a])
true
julia> transformed_output[2][:a] == add1(array_output[2][:a])
true
julia> transformed_output[3][:a] == add1(array_output[3][:a])
```

**Comment by rafaqz** [comment]
The source code is pretty simple:

https://github.com/cesaraustralia/DynamicGrids.jl/blob/2af4fe194ff861035140016878e1599f40898d9e/src/outputs/transformed.jl

You will see on line 49 that the function is actually applied to the whole NamedTuple of grids.

So probably you want `gs->map(sum, gs)`. Or `gs->@set gs[:a] = sum(gs[:a])`.

I dont know if this is the best behaviour, Im not really sure what it should do for muliple grids.

**Comment by rafaqz** [comment]
This output has barely been used at all by anyone, as far as I know. We should start marking things like this as experimental in the docs...

**Comment by rafaqz** [comment]
I think the error you have found is a weird quirk in `sum(::NamedTuple)` in Base:

```julia
julia> a = [1,2]
2-element Vector{Int64}:
 1
 2

julia> na = (; a)
(a = [1, 2],)

julia> b = sum(na)
2-element Vector{Int64}:
 1
 2

julia> b .*= 3
2-element Vector{Int64}:
 3
 6

julia> a
2-element Vector{Int64}:
 3
 6
```

`sum` is returning the same array, not a copy. So it gets updated in the next step as well. I'll have to deal with that potential.

**Comment by virgile-baudrot** [comment]
Fantastic
