### ISSUE TITLE
Failed to Precompile Julia 1.7

### ISSUE THREAD

**Issue by shenii** [cesaraustralia/DynamicGrids.jl#201]
I tried downloading DynamicGrids package using Julia 1.7, but an error message comes up. Is it possible to use package for this Julia version?

**Comment by rafaqz** [comment]
Yes I use it on 1.7...

Best to paste the code you use and the error here in a ``` code block, and we'll see what's up

**Comment by shenii** [comment]
Thanks. Pkg update seemed to fix the problem
