### ISSUE TITLE
ForestFire visualization

### ISSUE THREAD

**Issue by shenii** [cesaraustralia/DynamicGrids.jl#203]
<img width="1321" alt="fps" src="https://user-images.githubusercontent.com/32441862/149844408-af7ccaa2-da56-41a5-84b3-a886ff0bc377.png">

Trying to replicate the forest fire example, but an error comes up when saving the gif. I updated the QuartzImageIO package. Any suggestions I can try? Uploaded a screenshot.

**Comment by rafaqz** [comment]
Please no screenshots ;)

Instead it's best to always include code and errors in ``` code blocks. Much more readable and importantly can be copied and pasted. 

Also best to always include a minimum working example of all the code you ran to get to this error, and to check that you are on a recent version of DynamicGrids.jl. That way I can just run it and see what happens, and hopefully find you a solution quickly. This will take me a long time to track down, if I can even reproduce it.

**Comment by rafaqz** [comment]
But also as a guess, try installing ImageMagick and removing QuartzImageIO?

**Comment by shenii** [comment]
My apologies! Will do

**Comment by shenii** [comment]
'''
using DynamicGrids, ColorSchemes, Colors, BenchmarkTools, ImageMagick

const DEAD, ALIVE, BURNING = 1, 2, 3

neighbors_rule = let prob_combustion=0.0001, prob_regrowth=0.01
    Neighbors(Moore(1)) do data, neighborhood, cell, I
        if cell == ALIVE
            if BURNING in neighborhood
                BURNING
            else
                rand() <= prob_combustion ? BURNING : ALIVE
            end
        elseif cell == BURNING
            DEAD
        else
            rand() <= prob_regrowth ? ALIVE : DEAD
        end
    end
end

# Set up the init array and output (using a Gtk window)
init = fill(ALIVE, 400, 400)
output = GifOutput(init; 
    filename="forestfire.gif", 
    tspan=1:200, 
    fps=25, 
    minval=DEAD, maxval=BURNING, 
    scheme=ColorSchemes.rainbow,
    zerocolor=RGB24(0.0)
)

# Run the simulation, which will save a gif when it completes
sim!(output, neighbors_rule)

'''

**Comment by shenii** [comment]
'''
ERROR: MethodError: no method matching save_(::FileIO.File{FileIO.DataFormat{:GIF}, String}, ::Array{ARGB32, 3}; fps=25)
Closest candidates are:
  save_(::FileIO.File{R}, ::AbstractArray; permute_horizontal, mapi) where R<:FileIO.DataFormat at ~/.julia/packages/QuartzImageIO/4Fkqk/src/QuartzImageIO.jl:228 got unsupported keyword argument "fps"
  save_(::FileIO.Stream, ::AbstractArray; permute_horizontal, mapi) at ~/.julia/packages/QuartzImageIO/4Fkqk/src/QuartzImageIO.jl:326 got unsupported keyword argument "fps"

'''

**Comment by shenii** [comment]
I did also remove QuartzImageIO

**Comment by rafaqz** [comment]
Ok thanks. Last quibble us you need to use backticks ``` to get an equal spaced font thats readable as code. If you do ```julia it will be highlighted too :)

Did you try installing ImageMagick?

It seems to me the problem is QuartzImageIO.jl can't save a gif, which has to have frames per second `fps` argument.

I'll make it clearer in the readme which image saving libraries can save a gif. Its a bit odd with image libraries in that they are indirect dependencies.

Also try swapping in `GtkOutput` from DynamicGridsGtk.jl to just watch the simulation live.

**Comment by shenii** [comment]
I wonder if my issues were related to M-series Processor. I ended up using the following suggestion:
https://github.com/JuliaIO/ImageMagick.jl/issues/209

It works now in Jupyter Notebook (IJulia extension), but not in VSCode:)

**Comment by rafaqz** [comment]
Seems that could be the case. Looks like the update to ImageMagick_jll has fixed it?

**Comment by shenii** [comment]
Thanks!
