### ISSUE TITLE
Is there a way to disable GPU tests ?

### ISSUE THREAD

**Issue by ederag** [cesaraustralia/DynamicGrids.jl#205]
```julia
(test_DynamicGrids) pkg> test DynamicGrids
...
Warning: This version of CUDA.jl only supports NVIDIA drivers for CUDA 10.1 or higher (yours is for CUDA 9.1.0)
...
  InvalidIRError: compiling kernel gpu_ka_rule_kernel!(Cassette.Context{nametype(CUDACtx), ...
...
ERROR: LoadError: Some tests did not pass: 182 passed, 0 failed, 18 errored, 0 broken.
```
All failed tests are related to GPU (my drivers seem to be too old).
CUDA tests fail in a similar way, so it's *not* a DynamicGrids issue.

The obvious solution is driver update (just noticed it was still 390.144-lp153.31.1), but it's too scary right now.
Or dig into https://discourse.julialang.org/t/selective-testing/34736.

But there might be a simple way to disable GPU tests here ?

**Comment by rafaqz** [comment]
Currently no:
https://github.com/cesaraustralia/DynamicGrids.jl/blob/fa136b29006d2042555ca0329ba97725d2ccde6e/test/integration.jl#L5
https://github.com/cesaraustralia/DynamicGrids.jl/blob/fa136b29006d2042555ca0329ba97725d2ccde6e/test/rules.jl#L7

It just runs if you have a GPU. If you wan to add an environment variable to turn it off as part of these statements go for it.

**Comment by ederag** [comment]
```julia
if (
    get(ENV, "DYNAMICGRIDS_GPU_TESTS", "all") == "all"
    && CUDAKernels.CUDA.has_cuda_gpu()
)
...
```
works fine (if the variable is not set, it defaults to "all", which is the current behavior),
and with `ENV["DYNAMICGRIDS_GPU_TESTS"] = "none"` the GPU tests are skipped.

But it would be safer to centralize this (Q1) ?
Maybe in a function called `available_processor_flags()`, or `valid_processor_flags()` (Q2) ?
Where should it be (Q3) ?

But now I realize that integration.jl and in rules.jl differ:
https://github.com/cesaraustralia/DynamicGrids.jl/blob/fa136b29006d2042555ca0329ba97725d2ccde6e/test/integration.jl#L10
https://github.com/cesaraustralia/DynamicGrids.jl/blob/fa136b29006d2042555ca0329ba97725d2ccde6e/test/rules.jl#L11
Here the tests pass equally well with `hardware = (SingleCPU(), ThreadedCPU(), CPUGPU())` in both cases (nice !).
Is it possible to share the same code now (Q4) ?

**Comment by ederag** [comment]
Thanks. I was worried that the `DYNAMICGRIDS_GPU_TESTS` expected values might get out of sync,
if changed in one file but not the other. That would become hard to track.

After further search there is a way to disable CUDA but only at julia startup,
and alas, *here* it works only for the first call.
```julia
# This ought to work with an empty CUDA_VISIBLE_DEVICES instead of -1; maybe my drivers are too old.
CUDA_VISIBLE_DEVICES=-1  julia --project=.
julia> using CUDA
julia> CUDA.has_cuda_gpu()
false
julia> CUDA.has_cuda_gpu()
ERROR: CUDA error: initialization error (code 3, ERROR_NOT_INITIALIZED)
```
Time to upgrade the drivers, this week-end.

**Comment by ederag** [comment]
Now that https://github.com/JuliaGPU/CUDA.jl/issues/1331 is fixed
[*in master, not released yet, so I had to `(DynamicGrids) pkg> dev CUDA`, then remove CUDA from `Project.toml` to test*]
one may use
```julia
CUDA_VISIBLE_DEVICES=-1  julia --project=.
pkg> test DynamicGrids
...
     Testing DynamicGrids tests passed
```
to disable GPU.

----
*In case anyone would wonder as well:*
Since `CUDA_VISIBLE_DEVICES="0"` specifies the first GPU,
I'd have expected `CUDA_VISIBLE_DEVICES=""` to mean none,
and `CUDA_VISIBLE_DEVICES="-1"` to mean the last one,
but it's unfortunately not the case, according to https://github.com/JuliaGPU/CUDA.jl/issues/1336#issuecomment-1020861583.

**Comment by rafaqz** [comment]
Thanks for resolving this. Got to love zero based indexing choices, of course zero means one, and -1 means zero. Makes total sense
