### ISSUE TITLE
Error in example?

### ISSUE THREAD

**Issue by dfalster** [cesaraustralia/DynamicGrids.jl#29]
Hi team,

Was trying to run the example in the Readme and came across a possible bug

![image](https://user-images.githubusercontent.com/3589590/79310987-1d093a80-7f40-11ea-96f8-0cb91beb0fd3.png)

As a complete julia newb I had no idea how to fix, sorry!

**Comment by rafaqz** [comment]
Fixed :)

**Comment by dfalster** [comment]
Ah, that simple. Works!
