### ISSUE TITLE
Define neighborhood

### ISSUE THREAD

**Issue by shenii** [cesaraustralia/DynamicGrids.jl#54]
![Moore](https://user-images.githubusercontent.com/32441862/89355871-741b5280-d68a-11ea-8bd5-ed72967f96a6.jpeg)

Using your script for the forest fire model, I am getting an error for the Moore neighborhood. I tried defining neighborhood before the for loop but still having same issue.

**Comment by rafaqz** [comment]
Do you have an old version? Try running `] update` first.

It works fine for me on the latest version. Also note you need julia 1.2 > to use the latest version.

**Comment by shenii** [comment]
Thanks, it is working now on Jupyter notebook. I updated the IJulia package (Pkg.build)
