### ISSUE TITLE
handling vector/array within cells

### ISSUE THREAD

**Issue by virgile-baudrot** [cesaraustralia/DynamicGrids.jl#62]
Hi Raf,
I was thinking about using Array within Cell (to handle population traits within it, you may see where I'm going :-D).

I understand the structure should make it possible, but I did not find the way to make it working.
Since you can provide/return Tuple, maybe you choose to not using such approach?

In the follwoing example, maybe what I called "Tuple grid" is simpler, and maybe faster?, but for more complex ones, "Vector cell" would be easier to read.

"Tuple grid":
```julia
multirule = Cell{Tuple{:grid1,:grid2}, Tuple{:grid2,:grid3}}() do state1, state2
    state1 + state2, state1
end

init = (
    grid1 = rand(100,100),
    grid2 = zeros(100,100),
    grid3 = zeros(100,100)
)
output = REPLOutput(init; tspan=1:200, fps=30, color=Crayon(foreground=:red, background=:black, bold=true))
sim!(output, multirule)
output2 = ArrayOutput(init; tspan=1:200)
sim!(output2, multirule)
```

"Vector cell"
Note: during step defining the output, "ArrayOutput" return an error while "REPLOutput" doesn't. I expected the opposite. 
```julia
multirule2 = Cell{Tuple{:grid1,:grid2}, :grid2}() do state1, state2
    [state1 + state2, state1]
end

init = (
    grid1 = rand(100,100),
    grid2 = fill([0,0],100,100),
)
output = REPLOutput(init; tspan=1:200, fps=30, color=Crayon(foreground=:red, background=:black, bold=true))
sim!(output, multirule2)
output2 = ArrayOutput(init; tspan=1:200)
sim!(output2, multirule2)
```

All the best,
Virgile

**Comment by rafaqz** [comment]
Hi virgile, yes that's a good use case! 

So to summarise: your tuple example is writing single values to multiple grids, and your vector example writes multiple values to one grid. 

I'll try to give a few pointers on this. 

1. Tuples will be generally better than vectors - as tuples are bitstypes, and all actually stored in one grid. So reading them is efficient. 

2.`Vector`s are pointers to memory somewhere else - so they wont be cached well, and will be much slower, and not recommended.

3. You can do what you are trying to do with Vector, but with a grid of `Tuple`, or even better - define you own struct type for the traits. This will be faster, and have better dispatch flecibility than vectors or tuples.

4. The problem with complex grid types is going to be visualising them! If you use a custom struct, you can define dispatch methods for turning it into color somehow, or `>` for REPLoutput. You may need to define a specific processor to do this  - see processors.jl. But it shouldn't be too difficult.


If you want to post the error code I should be able to tell you whats going on, that does look like it should work for `ArrayOutput`

**Comment by rafaqz** [comment]
Ok so StaticArrays are the way to do this (besides writing a struct), instead of Tuple. StaticArrays define `zero` so they can be defined more easily than tuple, than don't define `zero`.

This constructs and runs fine:
```julia
using DynamicGrids, StaticArrays
multirule = Cell{Tuple{:grid1,:grid2}, :grid2}() do state1, state2
    state1 .+ state2
end

init = (
    grid1 = rand(100,100),
    grid2 = fill(SA[0.0, 0.0],100,100),
)
output = ArrayOutput(init; tspan=1:200)
sim!(output, multirule)
```

**Comment by rafaqz** [comment]
I added a little section to the readme/docs explaining this

**Comment by virgile-baudrot** [comment]
Fantastic, the example you provided work like a charm.
And, thank you for this detailled explanation, it's great you add the doc in the readme.

Defining a `struct` is indeed the best way to go. Also, connected to a closed issue talking about tracking individual compared to ABM , I feel like it's something actually feasible by playing with a `struct` (addind collection of ID).

**Comment by rafaqz** [comment]
You might also want to add some custom methods like this (not tested, see processors.jl in DynamicGrids for `rgb` reference):

```julia
DynamicGrids.rgb(A::SArray) = ARGB32(first(A))
Base.isless(A::SArray, x::Number) = isless(first(A), x)
Base.isless(x::Number, A::SArray, ) = isless(x, first(A))
```

They you should be able to visualise a grid of `SArray` like any other grid in REPLOutput and Gtk, Interact of Gif outputs

Also be sure to let me know how you go with these experiments :)

**Comment by virgile-baudrot** [comment]
Thank you Rafael.
Of course, I'll tell how things go. I'll be more focused on it early october.

**Comment by virgile-baudrot** [comment]
Hi Raf,

`SArray ` work fine with `Cell` rules, but it doesn't with `Neighbors`. The error message is the following:
`DimensionMismatch("array could not be broadcast to match destination")`
But as far as I understand, in the example below, it's `grid1` which is Read for neighbors, so there is no `SArray `.

```
using DynamicGrids, StaticArrays
ruleHood = Neighbors{Tuple{:grid1,:grid2}, :grid2}(Moore(1)) do neighborhood, state1, state2
    # sum(neighborhood) .+ state1 .+ state2
    state1 .+ state2
end

init = (
    grid1 = rand(100,100),
    grid2 = fill(SA[0.0, 0.0],100,100),
)
output = ArrayOutput(init; tspan=1:2)
sim!(output, ruleHood )
```

**Comment by rafaqz** [comment]
Oh right this is a similar problem to before. When it's a single value you can just broadcast, but its trying to broadcast the vector. I need to use `fill!(zero(T), size)` to initialise.

Writing things so any kind of object just works is a real skill.  I'll push through a fix in the next few hours. But I'll also write some tests to make sure that SArrray and structs work in everything else too, it seems we're going to need that.

**Comment by rafaqz** [comment]
Closed by $65
