### ISSUE TITLE
Automatically calculate the time index for all aux DimArrays with a `Ti` dimension.

### ISSUE THREAD

**Issue by rafaqz** [cesaraustralia/DynamicGrids.jl#84]
This would remove a lot of ugly technical code from Dispersal.jl, and also from examples in the upcoming methods paper.

We could also check the size of these arrays to make sure it matches the grid size. The problem with both of these things is we are making the firm assumption that any `DimArray` in `aux` is specifically tied to the spatial and temporal extend of the output, not some other random bit of data that a rule needs.

This assumption would also let us automatically permute and reorder `DimArray` to match the input arrays when the `Output` is constructed - which would remove a lot of setup code from our scripts.

@jamesmaino do you think this assumption is fine to make?

**Comment by jamesmaino** [comment]
But what if we have aux grids that don't have a Ti dimension, such as human pop density?

**Comment by rafaqz** [comment]
```julia
if hasdim(A, Ti) 
    calculate_the_index()
end
```

**Comment by rafaqz** [comment]
This is an example from the paper:

```julia

struct HostParasiteGrowth{R,W,M,P,Hs,Hh,A} <: CellRule{R,W}
    γ::M
    ρ::P
    Hsat::Hs
    Hhalf::Hh
    auxtimeindex::A
end

function DynamicGrids.applyrule(data, rule::HostParasiteGrowth, (H, P), index)
    γ = .........................................................
    rH = Dispersal.auxval(data, :rH, index..., rule.auxtimeindex)
    rP = Dispersal.auxval(data, :rP, index..., rule.auxtimeindex)
    h = .........................................
    β = ...................................
    R = ....................................
    δ = ..................................
    dHdt =...........................................
    dPdt = ...............................................
    ..........................
end

function DynamicGrids.precalcrule(rule::HostParasiteGrowth, data)
    Dispersal.precalc_auxtimeindex(aux(data, :rH), rule, data)
end
```

We need this precalc method, and we need to have `auxtimeindex` field in the rule. And we have this for about a quarter of the rules in Dispersal.jl.

Instead it would be:
```julia
auxval(data, :rP, index...)
```

And it would already know the time index for that aux array.

**Comment by jamesmaino** [comment]
Okay. So we need an error message like "aux dimension Ti should span the interval or the simulation"?

**Comment by rafaqz** [comment]
Yeah. Currently it just loops over it before/after the actual timespan it comes from... so it doesn't need a warning so badly, but the looping will be wrong for e.g. a `Week(1)` timestep because it doesn't fit into the year. 

It does really need the `Circular` mode rafaqz/GeoData.jl#60 so that it would give a warning like you say when it isn't `Circular`, and so that it could be `Circular(Year(1))` and would know to wrap at exactly one year instead of cycling over the timestep which might not fit into the year exactly.
