### ISSUE TITLE
Extending  `mapsetneighbor!`

### ISSUE THREAD

**Issue by virgile-baudrot** [cesaraustralia/DynamicGrids.jl#88]
I feel the need to extend the function `OutwardsDispersal` you defined in [`Dispersal.jl`](https://github.com/cesaraustralia/Dispersal.jl/blob/bd420b81e7d23c95c795c2aa0e40b88287f547d2/src/rules/kernel/outwards.jl#L2).

The thing, is that I needed to define a new version of `mapsetneighbor!`. It's working fine, but I don't know how generic it is, and if it has to be add in `DynamicGrids.jl`...
Or even better, I could do that without adding new version of `mapsetneighbor!`?

## Functions

So, in the following rule, I need the tuple `(state, weight)`.  The idea behind is to include a latent variable for dispersal: `state` refering to what I want to disperse, and `weight` comes from another grid (another population or a latent variable combining populations and many other stuff).

As we discussed earlier, I could build a struct with a `zero()` and `sum()`, but I found it's more flexible to avoid struct for that.

First, I build this new Abstract type `OutwardsWeightDispersal`:

```julia
abstract type OutwardsWeightDispersal{R,W} <: ManualNeighborhoodRule{R,W} end

@inline function applyrule!(data, rule::OutwardsWeightDispersal{R,W}, (state, weight), cellindex) where {R,W}
# 1. I don't need to redifine zero()
    state == zero(state) && return
    hood = neighborhood(rule)
# 2. after I extend  mapsetneighbor!() to allow handling weight variable
    sum = mapsetneighbor!(data[W], hood, rule, state, weight, cellindex)
    # Subtract from current cell, unless state is Bool
    state isa Bool || @inbounds return add!(data[W], -sum, cellindex...)
    return nothing
end
```
So here is the new rule `OutwardsWeightPopDispersal` and the extenstion of `mapsetneighbor!`

```julia
struct OutwardsWeightPopDispersal{R,W,NH} <: OutwardsWeightDispersal{R,W}
    "Normalised proportions of dispersal to surrounding cells"
    neighborhood::NH
end
OutwardsWeightPopDispersal{R,W}(;
    neighborhood=DispersalKernel{3}(),
) where {R,W} = OutwardsWeightPopDispersal{R,W}(neighborhood)

@inline function setneighbor!(
    data::WritableGridData, hood::Neighborhood, rule::OutwardsWeightPopDispersal,
    state::AbstractFloat, weight::AbstractFloat, hood_index, dest_index
)
    @inbounds propagules = state * weight * kernel(hood)[hood_index...]
    @inbounds add!(data, propagules, dest_index...)
    return propagules
end

@inline function mapsetneighbor!(
    data::WritableGridData, hood::Neighborhood, rule, state, weight, index
)
    r = radius(hood)
    sum = zero(state)
    # Loop over dispersal kernel grid dimensions
    for x = one(r):2r + one(r)
        xdest = x + index[2] - r - one(r)
        for y = one(r):2r + one(r)
            x == (r + one(r)) && y == (r + one(r)) && continue
            ydest = y + index[1] - r - one(r)
            hood_index = (y, x)
            dest_index = (ydest, xdest)
            sum += setneighbor!(data, hood, rule, state, weight, hood_index, dest_index)
        end
    end
    return sum
end
```

I think adding the possiblity of a `weight` variable to use like it `state * weight * kernel(hood)[hood_index...]` is quite generic
The idea is that this weight "grid" can be any latent variable that by chaining rule could result from a very complex computing.

## Examples

The simplest example:

```julia
pop = [ 10.0 0.0 0.0;
            0.0 5.0 10.0;
            2.0 5.0 0.0]
weight = [0.3 0.1 0.0;  
            0.0 0.0 0.0;
            0.0 0.0 0.0]

init = (pop=pop,
            weight = weight,)

output = ArrayOutput(init; tspan=1:3)
hood = DispersalKernel{1}(; formulation=ExponentialKernel(0.5))
rule = OutwardsWeightPopDispersal{Tuple{:pop,:weight},:pop}(;neighborhood=hood)
sim!(output, rule)
```

And a more complex one where structure would bring complexity:

```julia
init = (pop1 = pop,
           pop2 = pop,
           weight = weight,)

output = ArrayOutput(init; tspan=1:3)
# => Here I can easily define a new rule for the weight grid
ruleWeight = AnyCellRule{Tuple{:pop1,:pop2,:weight},:weight}(AnyAuxValues, AnyParameters, ...)

hood = DispersalKernel{1}(; formulation=ExponentialKernel(0.5))
ruleDispersal = OutwardsWeightPopDispersal{Tuple{:pop1,:weight},:pop1}(;neighborhood=hood)
ruleset = Ruleset(ruleWeight,ruleDispersal)
sim!(output, ruleset)
```

**Comment by rafaqz** [comment]
I actually want to depreciate `mapsetneighbor` and remove it before 1.0. I wrote a better alternative a few weeks ago, I just haven't gotten around to rewriting every use of it in Dispersal.jl.

Instead  of `mapsetneighbor` there are two iterators over neighbourhoods: `positions` and `offsets`. [offsets ](https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/src/neighborhoods.jl#L68) just give you the offset from the current index, and positions give you the [positions](https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/src/neighborhoods.jl#L28) of all neighbourhood cells in the main grid - simply by adding the current index to the offset.

So this loop will add some value to all the neighbours:

```julia
for pos in positions(neighborhood(rule), index)
    add!(data[Grid], somevalue, pos...)
end
```

Which should be much easier to use, and more flexible as its just an iterator. I couldn't get these to compile away when I started writing this so they weren't fast enough to use. But

Using `add!` safely adds to the neighbrhood cells. You shouldn't ever set cells directly unless you set them all to the same value, as you will overwrite previous writes from other cells. `add!` `sub!` and other methods like this also directly translate to `atomic_add!` etc on GPU.

Also, generally, inwards population dispersal is a better algorithm to use when you can. It paralellises better than outwards dispersal and has constant . In contrast, inwards neighbourhoods are basically a convolution, and can be optimised in a lot of ways to be very fast and are always safe as we only write to cells owned by the read/GPU worker.

**Comment by rafaqz** [comment]
I like the latent variable idea - but if we can do that easily in a general way would be better than having to formalise it.

**Comment by rafaqz** [comment]
We will also need to tweak the dispersal kernels a little if you want to index into them using the `offsets` iterator (I didn't think of this before).

We can make them an `OffsetArray` with `0, 0` at the center - so the indices match the offset you get with`offsets(rule)` 

So the kernel matrix would have the indices:

````julia
[(-1, -1), (-1, 0), (-1, 1),
 (0, -1 ), (0, 0 ), (0, 1 ),
 (1, -1 ), (1, 0 ), (1, 1 )]
```

**Comment by virgile-baudrot** [comment]
index at `0`, it's dissident to Julian mood :-D

**Comment by rafaqz** [comment]
This is actually indexing at -1 !! (and more generally at -R)

The options is to provide another iterator that just gives you the index for the kernel?

`kernelposition(neighborhood)` ?? Maybe a shorter name?

I don't know lol. We can do anything we want to! what would you prefer?

**Comment by virgile-baudrot** [comment]
I must mix several things.
I saw `buffer`function, when you convol `buffer(hood) . kernel(hood)`.
So, in `buffer(neighborhood)` you have the position of kernel maybe in Grids coordinates while `kernelposition(neighborhood)` would do it locally, by indexing -R:R centered in 0,0?
I feel like something like `centredbuffer`(neighborhood)` would be more explicite than `kernelposition(neighborhood)` 
Maybe I'm totally out...

**Comment by rafaqz** [comment]
`buffer()` gives you the buffer object for `Neighborhood` rules - so `InwardsDispersal`. It's how we make loading the neighborhood fast - indexing into the main array manually is slow. The rule is rebuilt around a new buffer array for every single cell (it compiles away). 

`buffer(hood)` is not meant to be used by users. `neighbors(hood)` returns it anyway for a `DispersalKernel` neighborhood iterable - a matrix is an iteratable .I probably need to change buffer to `_buffer` so its clearly "don't touch".

I'll do this for all of the low-level methods to make this clearer.

`offsets`, `positions` and `kernelpositions` I'm proposing are for `OutwardsDispersal` and other `ManualNeighborhood` - and they don't have a buffer, as the idea is it writes _to_ the neighborhood, instead of reading from it. You'll notice Inwards and Outwards can have identical results (the Dispersal.jl tests show this) - it's mostly a performance or stylistic choice as to which you should use for something.

Its maybe a little confusing still. I'm working this out as I go. Any suggestions on improved names and communication would be great.

**Comment by rafaqz** [comment]
I was thinking `kernelposition(neighborhood)` would return an iterable like

`((1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3))`

**Comment by virgile-baudrot** [comment]
Thank you, it's clearer now. So yes, about naming, `kernelposition` seems great.

**Comment by rafaqz** [comment]
Great. Your pretty much the first person who has actually tried to understand this code. 

I'll try to update Dispersal.jl when I have some time and see if `kernelposition` makes sense in practice.
