### ISSUE TITLE
Rename ManualRule, ManualNeighborhoodRule and Manual

### ISSUE THREAD

**Issue by rafaqz** [cesaraustralia/DynamicGrids.jl#92]
Rules that have to modify a grid manuully in `applyrule!` are called `ManualRule`, with ManualNeighborhoodRule for the neighborhood version (the difference is the grid will be padded for you, and writing outside of the neighborhood has undefined behaviour. `Manual` is the shorthand `ManualRule`. But it seems kind of confusing as a name.

My current thoughts are these three could be:

`SetCellRule, SetNeighborhoodRule, SetCell`

To reflect that you have to actively set something instead of the result being written to the cell for you. We already have `SetNeighborood` for the `ManualNeighborhoodRule`, so this naming scheme would tie everything together.

The main caveat is that we actually shouldn't use `setindex!` most of the time - but use `add!` `sub!` `min!` `max!` etc instead. So `set` is not really an accurate description. But I'm not sure what is better.

@jamesmaino @virgile-baudrot any ideas on this?

**Comment by virgile-baudrot** [comment]
I like `SetCellRule`.
But if you want to avoid `set`,  what about `MakeCellRule` and `MakeNeighborhoodRule`? 
or `CreateCellRule` but a `CellRule` has also to be create, or `PersonalizeCellRule` but this one is to long to write.

**Comment by jamesmaino** [comment]
I think `SetCellRule` etc is okay to me.

**Comment by rafaqz** [comment]
Great I'll lock that in then.
