### ISSUE TITLE
Finalise ImageProcessor interface

### ISSUE THREAD

**Issue by rafaqz** [cesaraustralia/DynamicGrids.jl#93]
The `Processor` suffix is pretty vague

`ColorProcessor`, `LayoutProcessor` etc.

But - we can attempt to hide these from users as much as possible so it may not matter. What is important is that the interface for writing new ones is finalised.

ImageProcessor and TextConfig code is here:
https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/src/outputs/processors.jl
https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/src/outputs/textconfig.jl

@jamesmaino it would be great to get a sanity check on some of the naming conventions and functions I'm using.

**Comment by jamesmaino** [comment]
Processor is intuitive to me. I think the important thing is that there are defaults that work (even if ugly) and the user can then dig into the processors if they are motivated.

**Comment by rafaqz** [comment]
@jamesmaino we have those defaults written already, this is just about naming things.
