### ISSUE TITLE
Dot product of structs and SArrays

### ISSUE THREAD

**Issue by rafaqz** [cesaraustralia/DynamicGrids.jl#95]
@jamesmaino and @virgile-baudrot  I've been looking into getting dispersal kernels working for objects.

So in julia, and in linear algera generally (I guess?) the dot product is recursive - `dot` is called on the matrix contents as well as on the matrices themselves - so dot multiplication of matrices of vectors still returns a scalar, not a vector. 

But we don't want that behaviour. We want the dot product over a neighborhood of grid values to return a new grid value of the same type. If it's an object, we want an object. If it's a vector, we want a new vector. We want the dot-product of the element-wise multiplication of the kernel and neighborhood values - not the real dot product.

We can hack this for custom objects by defining:

```julia
LinearAlgebra.dot(x::Number, y::MyStruct) = x * y
```

Assuming we have already defined `Base.:*` for scalar multiplication by our object. But we can't do this for vector types like SArray without type-pyracy.

So the question is - do we 
1. Not support StaticArray dispersal, and users must define `LinearAlgebra.dot` between their object and the kernel values (probably a scalar `Number`)
2. Use our own kernel product definition that just multiplies the kernel/window values as if they are scalars, so only `*` needs to be defined for an object

Technically I guess what we want is the sum of the hadamard product of the kernel and the neighborhood, but I'm not really across linear algebra so if either of you can classify this better that would be great.

**Comment by virgile-baudrot** [comment]
It may have some possiblity  by using identity matrix between  StaticArray object and the other matrix to multiply. But even if it's possible it increases exponentially the number of operation.

So I agree with you, not supporting StaticArray dispersal would be good to make it more explicit to the user that using `StaticArray` in a grid cell  has not the properties of a vector or a matrix in the mathematical meaning, it's just an frame for an object which can be store in a StaticArray.

**Comment by jamesmaino** [comment]
Happy to leave it to the user to define `LinearAlgebre.dot`. We cannot think of all use cases here.
