### ISSUE TITLE
Rename `init` to `grid`

### ISSUE THREAD

**Issue by rafaqz** [cesaraustralia/DynamicGrids.jl#96]
This would make it clearer what `init` was for, and remove one word from the vocabulary.

Any thoughts on this @jamesmaino  and @virgile-baudrot ?

**Comment by jamesmaino** [comment]
I think `init` is clearer. When we write something like `sim!(output, rulset; init=init)` I think `init` distinguishes itself from `output` more than `grid`.

**Comment by rafaqz** [comment]
Ok fair enough.
